### ISSUE TITLE
Als team willen we Tom Kemper spreken om zijn kijk op het project te zien en ons architectuurplaatje voor te leggen, zodat wij een beter beeld kunnen schetsen van het probleem en oplossing

### ISSUE THREAD

**Issue by matthewjb02** [matthewjb02/Test-Repo-INNO#18]
## Definiton of Done
- [ ] We hebben een beter beeld over de applicatie en de mogelijke oplossing 
- [ ] We hebben ons architectuurplaatje voorgelegd en krijgen feedback

## Tasks
- [ ] Architectuurplaatje maken
- [ ] Een afspraak maken met Tom
