### ISSUE TITLE
Als developers willen we een opzet hebben van een lokale REST-API in Flask zodat we een MVP back-end hebben.

### ISSUE THREAD

**Issue by matthewjb02** [matthewjb02/Test-Repo-INNO#19]
## Definition of Ready
- [x] Everyone agrees that the quality of the story is OK.
- [x] No team member has a question about the description.
- [x] The description is clear so everyone knows what to do.
- [x] The Definiton of Done is all checked and approved.

## Definiton of Done
- [ ] Er is een opzet voor een REST-API in Flask Python

## Tasks
- [x] Importeer flask
- [x] Maak een basis opzet van een REST-API zonder endpoints
