### ISSUE TITLE
Als developer wil ik kennis over Python opfrissen, zodat ik in staat ben te begrijpen hoe de huidige MVP werkt

### ISSUE THREAD

**Issue by matthewjb02** [matthewjb02/Test-Repo-INNO#21]
## Definiton of Done
- [x] We hebben weer basiskennis over python
- [x] We begrijpen hoe python scripts werken

## Tasks
- [x] De READme.md van het canvas dashboard lezen
- [x] Proberen lokaal de python scripts te runnen
- [x] Python Course 1 -> https://www.youtube.com/watch?v=ix9cRaBkVe0&list=LL&index=2
- [x] Opgedane kennis toepassen om de python scripts te studeren en te begrijpen hoe ze worden gegenereerd
