### ISSUE TITLE
Als developer wil ik kennis over Flask opdoen, zodat ik in staat ben te beginnen met de eerste MVP van de back-end REST-API.

### ISSUE THREAD

**Issue by matthewjb02** [matthewjb02/Test-Repo-INNO#22]
## Definiton of Done
- [x] We hebben basiskennis over Flask
- [x] We hebben een beter beeld over hoe we een Flask REST-API kunnen toepassen in het project 

## Tasks
- [x] Flask course 1 -> https://youtube.com/playlist?list=PL-osiE80TeTs4UjLw5MM6OjgkjFeUxCYH&feature=shared
