### ISSUE TITLE
Als developers wil ik uitzoeken hoe we technisch inlog functionaliteit kunnen realiseren

### ISSUE THREAD

**Issue by matthewjb02** [matthewjb02/Test-Repo-INNO#23]
## Definiton of Done
- [ ] We hebben een beter beeld over de applicatie en de mogelijke oplossing 
- [ ] We hebben indien mogelijk nieuwe requirements toegevoegd aan ons planboard

## Tasks
- [ ] Een afspraak maken met Tom
