### ISSUE TITLE
Als developers willen wij de data uit de python scripts voor nu opslaan in een mongoDB zodat we deze data kunnen weergeven in de front-end van de REST-API

### ISSUE THREAD

**Issue by matthewjb02** [matthewjb02/Test-Repo-INNO#24]
## Definition of Ready
- [ ] Everyone agrees that the quality of the story is OK.
- [ ] No team member has a question about the description.
- [ ] The description is clear so everyone knows what to do.
- [ ] The Definiton of Done is all checked and approved.

## Definiton of Done
- [ ] We hebben een beter beeld over de applicatie en de mogelijke oplossing 
- [ ] We hebben indien mogelijk nieuwe requirements toegevoegd aan ons planboard

## Tasks
Todo
