### ISSUE TITLE
Als CSC'ers willen we dockerizen voor de cloudomgeving, zodat het meer flexibel is

### ISSUE THREAD

**Issue by matthewjb02** [matthewjb02/Test-Repo-INNO#27]
## Definition of Ready
- [ ] Everyone agrees that the quality of the story is OK.
- [ ] No team member has a question about the description.
- [ ] The description is clear so everyone knows what to do.
- [ ] The Definiton of Done is all checked and approved.

## Definiton of Done
?

## Tasks
?
