### ISSUE TITLE
Als gebruiker wil ik dat alleen mijn data wordt laten zien zodat er geen schending van privacy voordoet

### ISSUE THREAD

**Issue by JeroenCab** [matthewjb02/Test-Repo-INNO#4]
## Definition of Ready
- [ ] Everyone agrees that the quality of the story is OK.
- [ ] No team member has a question about the description.
- [ ] The description is clear so everyone knows what to do.
- [ ] The Definiton of Done is all checked and approved.

## Definiton of Done
- [ ] Er is context beschikbaar over de student is ingelogd

## Tasks
todo

**Comment by matthewjb02** [comment]
hoort in 4
