### ISSUE TITLE
Als docent wil ik op de index.html van de nu nog lokale Flask API een dashboard hebben, zodat ik de data van alle studenten kan zien.

### ISSUE THREAD

**Issue by JeroenCab** [matthewjb02/Test-Repo-INNO#5]
## Definition of Ready
- [x] Everyone agrees that the quality of the story is OK.
- [x] No team member has a question about the description.
- [x] The description is clear so everyone knows what to do.
- [x] The Definiton of Done is all checked and approved.

## Definiton of Done
- [ ] op de index.html is er een endpoint naar het dashboard voor de docent

## Tasks
- [x] Onderzoek naar waar de html wordt gegenereerd
- [x] Maak een nieuw endpoint voor de index.html
- [x] Serve de front end van het  dashboard voor de docent aar naar een endpoint in de Flask API
